server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /images/ {
        try_files $uri @backend_images;
    }

    location @backend_images {
        proxy_pass https://callejon-backend-836176703716.us-central1.run.app;
        proxy_set_header Host callejon-backend-836176703716.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /api/ {
        proxy_pass https://callejon-backend-836176703716.us-central1.run.app;
        proxy_set_header Host callejon-backend-836176703716.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /ws {
        proxy_pass https://callejon-backend-836176703716.us-central1.run.app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host callejon-backend-836176703716.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
